### PR TITLE
tools/dt-validate: filter error messages from disabled subnodes

### PR DESCRIPTION
**Pull request by benjamingaignard**
Ignore errors on disabled subnodes.

Signed-off-by: Benjamin Gaignard <benjamin.gaignard@st.com>

### CODE REVIEW

**Comment by robherring** [comment]
The tooling is supposed to handle disabled nodes already in the case of missing required properties. There could easily be some shortcoming in the handling of this. Is this case not working for you or it's something different?

I'm reluctant to just turn off the checking.

**Comment by benjamingaignard** [comment]
It is related to this issue: https://github.com/devicetree-org/dt-schema/issues/32

Disabled nodes case is already handled but when a parent node is enabled and a child node disabled we can have warning about missing required properties.
For example that is the case with the schema in st,stm32-adc.yaml because the adc core is enabled by the SoC when the channels are depending of the board. This led to a situation where dtbs_check wrongly claims that the dtb isn't valid.

trace from dtbs_check: adc@40012000 node is enabled but adc@0 child status is disabled
arch/arm/boot/dts/stm32429i-eval.dt.yaml: adc@40012000: adc@0: {'clocks': [[1, 0, 168]], 'dma-names': ['rx'], 'status': ['disabled'], 'dmas': [[14, 0, 0, 1024, 0]], 'reg': [[0]], 'interrupt-parent': [[19]], '#io-channel-cells': [[1]], 'compatible': ['st,stm32f4-adc'], 'interrupts': [[0]]} is not valid under any of the given schemas (Possible causes of the failure):
	/mnt/data/linux-yaml/arch/arm/boot/dts/stm32429i-eval.dt.yaml: adc@40012000: adc@0: 'st,adc-channels' is a required property

**Comment by benjamingaignard** [comment]
if it is too problematic to turn off the checking, could we imagine to check the status inside the yaml file itself with something like if: properties: status: contains: "disabled" -> ignore the fields ?

**Comment by robherring** [comment]
I think the check above the one you added should be improved to handle child nodes. IIRC, the error structure should have the path of the error, so we should be able to check if the error path contains 'status'.

**Comment by benjamingaignard** [comment]
The check above discard the errors messages for disabled parent node, right ?
If the parent is disabled missing properties in the child node won't generate error.

**Comment by robherring** [comment]
#44 solves the same issue.

**Comment by benjamingaignard** [comment]
I have done test and #44 doesn't solve the problem.
If a property is missing in a disabled subnode the warning still occur.
It is reproductible on stm32 DT. You will get this error
adc@40012000: adc@100: {'interrupts': [[1]], 'dma-names': ['rx'], 'reg': [[256]], 'dmas': [[14, 3, 1, 1024, 0]], 'status': ['disabled'], '#io-channel-cells': [[1]], 'clocks': [[1, 0, 169]], 'interrupt-parent': [[19]], 'compatible': ['st,stm32f4-adc']} is not valid under any of the given schemas (Possible causes of the failure):
	/mnt/data/linux-yaml/arch/arm/boot/dts/stm32429i-eval.dt.yaml: adc@40012000: adc@100: 'st,adc-channels' is a required property

**Comment by robherring** [comment]
The problem here has nothing to do with child nodes. That may have originally been one of the problems, but Thierry fixed that part. The problem is in the schema when 'required' is under a 'oneOf'. So the error message is a sub error which is in error.context. I've pushed a fix for this.

**Pull request closed without merging**
